import React from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { Settings, clearHistory } from "../storage";

type Props = {
  settings: Settings;
  onChangeSettings: (s: Settings) => void;
  onClearedHistory: () => void;
};

export function AboutScreen({ settings, onChangeSettings, onClearedHistory }: Props) {
  const handleClear = () => {
    if (typeof Alert !== "undefined" && Alert.alert) {
      Alert.alert(
        "Clear history?",
        "All saved readings will be permanently removed.",
        [
          { text: "Cancel", style: "cancel" },
          {
            text: "Clear",
            style: "destructive",
            onPress: async () => {
              await clearHistory();
              onClearedHistory();
            },
          },
        ],
      );
    }
  };

  return (
    <ScrollView contentContainerStyle={styles.scroll}>
      <View style={styles.header}>
        <Text style={styles.title}>About</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Lucky Numbers</Text>
        <Text style={styles.body}>
          A playful number generator that blends numerology with the local time and a dash of
          randomness — or daily picks tied to your astrological sign. Every reading is for
          entertainment only.
        </Text>
        <Text style={styles.version}>Version 0.1.0</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>How it works</Text>
        <Text style={styles.body}>
          Numerology readings combine your Life Path, Expression, and Origin numbers with the
          current day's energy, the minute of the request, and a fresh random seed — so the
          numbers shift each time you tap Generate.
        </Text>
        <Text style={[styles.body, { marginTop: 8 }]}>
          Horoscope readings draw from your sign and today's date. Tap Regenerate to get a
          different set.
        </Text>
      </View>

      <View style={styles.section}>
        <View style={styles.row}>
          <View style={{ flex: 1 }}>
            <Text style={styles.rowTitle}>Personalized ads</Text>
            <Text style={styles.rowSubtitle}>
              Allow AdMob to use limited data for relevant ads.
            </Text>
          </View>
          <Switch
            value={settings.personalizedAds}
            onValueChange={(v) => onChangeSettings({ ...settings, personalizedAds: v })}
          />
        </View>
      </View>

      <View style={styles.section}>
        <Pressable onPress={handleClear} style={({ pressed }) => [styles.danger, pressed && { opacity: 0.7 }]}>
          <Text style={styles.dangerText}>Clear saved history</Text>
        </Pressable>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Disclaimer</Text>
        <Text style={styles.body}>
          Lucky Numbers is for entertainment purposes only. It is not affiliated with, endorsed
          by, or sponsored by any lottery, the Multi-State Lottery Association, the California
          State Lottery, or any government agency. Numbers generated by this app have no greater
          chance of winning than any other random set. Please play responsibly. You must be of
          legal age in your jurisdiction to participate in lottery games.
        </Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  scroll: { paddingBottom: 24 },
  header: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 8 },
  title: { color: "#fff", fontSize: 26, fontWeight: "800" },
  section: {
    marginHorizontal: 16,
    marginTop: 12,
    padding: 16,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  sectionTitle: {
    color: "#fde68a",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  body: { color: "rgba(255,255,255,0.75)", fontSize: 13, lineHeight: 19 },
  version: { color: "rgba(255,255,255,0.4)", fontSize: 11, marginTop: 10 },
  row: { flexDirection: "row", alignItems: "center" },
  rowTitle: { color: "#fff", fontSize: 14, fontWeight: "700" },
  rowSubtitle: { color: "rgba(255,255,255,0.55)", fontSize: 11, marginTop: 2 },
  danger: { paddingVertical: 12, alignItems: "center", borderRadius: 10, backgroundColor: "rgba(225,29,72,0.15)" },
  dangerText: { color: "#fda4af", fontWeight: "700", fontSize: 14 },
});
